/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pxltiger (https://sketchfab.com/pxltiger)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fantasy-landscape-b86ceddee3394444818bb3ed4a4773d8
title: Fantasy Landscape
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import fantasy from '../../assets/modele3D/fantasy.gltf';

export default function Fantasy({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(fantasy)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[8.36, 20.44, -704.34]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Rock1_Rock_0.geometry} material={materials.Rock} />
          </group>
          <group position={[59.15, -112.58, -331.75]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.GroundRoad_Ground_road_0.geometry} material={materials.Ground_road} />
          </group>
          <group position={[853.82, -16.2, -62.23]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Grass010_Plant_0.geometry} material={materials.Plant} />
          </group>
          <group position={[884.32, -12.84, -351.68]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Birch_tree2_Birch_bark_0.geometry} material={materials.Birch_bark} />
            <mesh geometry={nodes.Birch_tree2_Birch_leaves_0.geometry} material={materials.Birch_leaves} />
          </group>
          <group position={[61.11, -12.84, -1172.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Birch_tree3_Birch_bark_0.geometry} material={materials.Birch_bark} />
            <mesh geometry={nodes.Birch_tree3_Birch_leaves_0.geometry} material={materials.Birch_leaves} />
          </group>
          <group position={[59.15, -112.58, -331.75]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.GroundGrass_Ground_grass_0.geometry} material={materials.Ground_grass} />
          </group>
          <group position={[-239.97, 12.61, -82.34]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Deciduous_tree1_Tree_bark1_0.geometry} material={materials.Tree_bark1} />
            <mesh geometry={nodes.Deciduous_tree1_Tree_leaves1_0.geometry} material={materials.Tree_leaves1} />
          </group>
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload(fantasy)
